name = "sync"
description = "Synchronisation primitives for thread-syncing"

dependencies = [
   "kernel",
]

sources = [
  "mutex.cpp",
]

public_headers = [
  "public_headers/mutex.hpp -> cyros/sync/mutex.hpp",
]

