name = "kernel"
kind = "core"

sources = [
  "kernel.cpp",
  "scheduler.cpp",
  "threading_subsystem.cpp",
  "waitable.cpp",
  "spinlock.cpp",
]

sources_excluded_from_archive = [
  "validate_config.cpp"
]

public_headers = [
  "public_headers/kernel.hpp -> cyros/kernel/kernel.hpp",
  "public_headers/function.hpp -> cyros/kernel/function.hpp",
  "public_headers/spinlock.hpp -> cyros/kernel/spinlock.hpp",
  "public_headers/thread.hpp -> cyros/kernel/thread.hpp",
  "public_headers/waitable.hpp -> cyros/kernel/waitable.hpp",
  "public_headers/core.hpp -> cyros/kernel/core.hpp",
]
