name = "kernel"
kind = "core"

sources = [
  "kernel.cpp",
  "scheduler.cpp",
  "waitable.cpp",
  "threading_subsystem.cpp"
]

sources_excluded_from_archive = [
  "validate_config.cpp"
]

public_headers = [
  "public_headers/kernel.hpp -> cortos/kernel/kernel.hpp",
  "public_headers/function.hpp -> cortos/kernel/function.hpp",
  "public_headers/spinlock.hpp -> cortos/kernel/spinlock.hpp",
  "public_headers/thread.hpp -> cortos/kernel/thread.hpp",
  "public_headers/waitable.hpp -> cortos/kernel/waitable.hpp",
]
