name = "linux_coop"

sources = [
   "port_linux_coop.cpp",
   "port_time_linux_coop.cpp",
   "../common/port_linux_common.cpp",
]

private_includes = [
   "../common",
]

public_headers = [
   "public_headers/port_traits.h -> cyros/port/port_traits.h",
]
